# https://megalinter.io
---
name: MegaLinter

# yamllint disable-line rule:truthy - false positive
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: MegaLinter
        # kics-scan ignore-line
        uses: oxsecurity/megalinter@v9
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE: COPYPASTE,SPELL
